# Path where the test ontology file reside
ont_inpath: "./modules/"

# Path where the generated adoc-fragments for classes will be stored
# CAUTION: The content of this path will be deleted every time Rdfdoc is started!!!
adoc_class_outpath: "./fragments/classes/"

# Path where the generated adoc-fragments for properties will be stored
# CAUTION: The content of this path will be deleted every time rdf2adoc is started!!!
adoc_prop_outpath: "./fragments/properties/"

# Path where the generated Reference document adoc-fragments for classes will be stored
# CAUTION: The content of this path will be deleted every time Rdfdoc is started!!!
reference_class_outpath: "./fragments/reference_classes/"

# Path where the generated Reference document adoc-fragments for properties will be stored
# CAUTION: The content of this path will be deleted every time rdf2adoc is started!!!
reference_prop_outpath: "./fragments/reference_properties/"

# Path where the generated PlantUMl files will be stored
# CAUTION: The content of this path will be deleted every time rdf2adoc is started!!!
puml_outpath: "./fragments/puml/"

# Path where the generated Reference document will be stored
# CAUTION: The content of this path will be deleted every time rdf2adoc is started!!!
reference_outpath: "./reference/"

# Path where the generated WebVOWL diagrams will be stored
# CAUTION: The content of this path will be deleted every time rdf2adoc is started!!!
diag_outpath: "./webvowl_diagrams/"

# Path to the plantuml.jar for png diagram creation
plantuml_jar: "./plantuml.jar"

# Set to True if you want to have diagram generation
diag_gen: False

# Set to True if you want to have logging in a logfile
logging: True

# Logging file name
logfile: "rdf2adoc.log"


