# Path where the TTL files reside
ont_inpath: "C:\\\\Users\\\\tambarian\\\\Desktop\\\\ASAM_OxO_doc\\\\modules\\\\OpenXOntologyHQDM.ttl"

# Path where the generated adoc-fragments for classes will be stored
# CAUTION: The content of this path will be deleted every time Rdfdoc is started!!!
adoc_class_outpath: "C:\\\\Users\\\\tambarian\\\\Desktop\\\\ASAM_OxO_doc\\\\fragments\\\\current\\\\classes\\\\"

# Path where the generated adoc-fragments for properties will be stored
# CAUTION: The content of this path will be deleted every time Rdfdoc is started!!!
adoc_prop_outpath: "C:\\\\Users\\\\tambarian\\\\Desktop\\\\ASAM_OxO_doc\\\\fragments\\\\current\\\\properties\\\\"

# Set to True if you want to have logging in a logfile
logging: True

# Logging file name
logfile: "rdfdoc.log"


