# Path where the TTL file reside
ont_inpath: "./modules/corePlus20210722.ttl"

# Path where the generated adoc-fragments for classes will be stored
# CAUTION: The content of this path will be deleted every time Rdfdoc is started!!!
adoc_class_outpath: "./fragments/classes/"

# Path where the generated adoc-fragments for properties will be stored
# CAUTION: The content of this path will be deleted every time rdf2adoc is started!!!
adoc_prop_outpath: "./fragments/properties/"

# Set to True if you want to have logging in a logfile
logging: True

# Logging file name
logfile: "rdfdoc.log"


