@startuml
Title ActivityState 

Card ActivityState #F0F8FF [
ActivityState
----
- causes : Event 
- hasParticipant : Participant 
]
Card State #F0F8FF [
State
]
State --|> ActivityState  #00008B 
Card WholeLifeActivity #F0F8FF [
WholeLifeActivity
]
WholeLifeActivity <|-- ActivityState  #00008B 
@enduml