@startuml
Title Aggregation 

Card Aggregation #F0F8FF [
Aggregation
----
- part : SpatioTemporalExtent 
- whole : SpatioTemporalExtent 
]
Card Relationship #F0F8FF [
Relationship
]
Relationship --|> Aggregation  #00008B 
Card Composition #F0F8FF [
Composition
]
Composition <|-- Aggregation  #00008B 
@enduml