@startuml
Title AngleQuantity 

Card AngleQuantity #F0F8FF [
AngleQuantity
]
Card PhysicalQuantity #F0F8FF [
PhysicalQuantity
----
- approximatelyEqualTo : PhysicalQuantity 
- defines : PhysicalQuantity 
- hasQuantityRelation : PhysicalQuantity 
- quantityEqualTo : PhysicalQuantity 
- quantityGreaterThan : PhysicalQuantity 
- quantityGreaterThanOrEqualTo : PhysicalQuantity 
- quantityLessThan : PhysicalQuantity 
- quantityLessThanOrEqualTo : PhysicalQuantity 
- quantityNotEqualTo : PhysicalQuantity 
]
PhysicalQuantity --|> AngleQuantity  #00008B 
@enduml