@startuml
Title BiologicalObjectState 

Card BiologicalObjectState #F0F8FF [
BiologicalObjectState
]
Card PhysicalObjectState #F0F8FF [
PhysicalObjectState
----
- connectedTo : PhysicalObjectState 
- hasRelativePosition : PhysicalObjectState 
]
PhysicalObjectState --|> BiologicalObjectState  #00008B 
Card WholeLifeBiologicalObject #F0F8FF [
WholeLifeBiologicalObject
]
WholeLifeBiologicalObject <|-- BiologicalObjectState  #00008B 
@enduml