@startuml
Title Composition 

Card Composition #fff [
Composition
]
Card Aggregation #fff [
Aggregation
----
- part : SpatioTemporalExtent 
- whole : SpatioTemporalExtent 

]
Aggregation --|> Composition  #000 
@enduml