@startuml
Title ConnectionRelation 

Card ConnectionRelation #F0F8FF [
ConnectionRelation
]
Card DefinedRelationship #F0F8FF [
DefinedRelationship
----
- involves : Classification 
]
DefinedRelationship --|> ConnectionRelation  #00008B 
Card SpatialConnection #F0F8FF [
SpatialConnection
]
ConnectionRelation --|> SpatialConnection  #00008B 
@enduml