@startuml
Title ControllerObject 

Card ControllerObject #F0F8FF [
ControllerObject
----
- controls : SpatioTemporalExtent 
]
Card State #F0F8FF [
State
]
State --|> ControllerObject  #00008B 
@enduml