@startuml
Title DefinedRelationship 

Card DefinedRelationship #F0F8FF [
DefinedRelationship
----
- involves : Classification 
]
Card Relationship #F0F8FF [
Relationship
]
Relationship --|> DefinedRelationship  #00008B 
Card ConnectionRelation #F0F8FF [
ConnectionRelation
]
ConnectionRelation <|-- DefinedRelationship  #00008B 
Card SpatialRelation #F0F8FF [
SpatialRelation
----
- hasRelationDirection : DirectionQuantity 
- hasSpatialObject : PhysicalObjectState 
- hasSpatialSubject : PhysicalObjectState 
]
SpatialRelation <|-- DefinedRelationship  #00008B 
Card TemporalRelation #F0F8FF [
TemporalRelation
]
TemporalRelation <|-- DefinedRelationship  #00008B 
@enduml