@startuml
Title DirectionQuantity 

Card DirectionQuantity #F0F8FF [
DirectionQuantity
----
- oppositeOf : DirectionQuantity 
- parallelTo : DirectionQuantity 
]
Card PhysicalQuantity #F0F8FF [
PhysicalQuantity
----
- approximatelyEqualTo : PhysicalQuantity 
- defines : PhysicalQuantity 
- hasQuantityRelation : PhysicalQuantity 
- quantityEqualTo : PhysicalQuantity 
- quantityGreaterThan : PhysicalQuantity 
- quantityGreaterThanOrEqualTo : PhysicalQuantity 
- quantityLessThan : PhysicalQuantity 
- quantityLessThanOrEqualTo : PhysicalQuantity 
- quantityNotEqualTo : PhysicalQuantity 
]
PhysicalQuantity --|> DirectionQuantity  #00008B 
@enduml