@startuml
Title DrivableConnection 

Card DrivableConnection #F0F8FF [
DrivableConnection
]
Card SpatialConnection #F0F8FF [
SpatialConnection
]
SpatialConnection --|> DrivableConnection  #00008B 
@enduml