@startuml
Title Event 

Card Event #F0F8FF [
Event
----
- hasRelativeTime : Event 
]
Card SpatioTemporalExtent #F0F8FF [
SpatioTemporalExtent
----
- aggregatedInto : SpatioTemporalExtent 
- hasPart : SpatioTemporalExtent 
]
SpatioTemporalExtent --|> Event  #00008B 
Card PointInTime #F0F8FF [
PointInTime
]
PointInTime <|-- Event  #00008B 
@enduml