@startuml
Title FunctionalSystemComponentState 

Card FunctionalSystemComponentState #F0F8FF [
FunctionalSystemComponentState
]
Card FunctionalObjectState #F0F8FF [
FunctionalObjectState
----
- intendedRole : Role 
]
FunctionalObjectState --|> FunctionalSystemComponentState  #00008B 
Card SystemComponentState #F0F8FF [
SystemComponentState
----
- componentOf : SystemState 
]
SystemComponentState --|> FunctionalSystemComponentState  #00008B 
Card InstalledFunctionalSystemComponent #F0F8FF [
InstalledFunctionalSystemComponent
]
FunctionalSystemComponentState --|> InstalledFunctionalSystemComponent  #00008B 
Card RoadObject #F0F8FF [
RoadObject
----
- driveableTo : RoadObject 
- hasPredecessor : RoadObject 
- hasSuccessor : RoadObject 
]
FunctionalSystemComponentState --|> RoadObject  #00008B 
@enduml