@startuml
Title FunctionalSystemState 

Card FunctionalSystemState #F0F8FF [
FunctionalSystemState
]
Card FunctionalObjectState #F0F8FF [
FunctionalObjectState
----
- intendedRole : Role 
]
FunctionalObjectState --|> FunctionalSystemState  #00008B 
Card SystemState #F0F8FF [
SystemState
]
SystemState --|> FunctionalSystemState  #00008B 
@enduml