@startuml
Title Geometry 

Card Geometry #F0F8FF [
Geometry
]
Card PhysicalProperty #F0F8FF [
PhysicalProperty
]
PhysicalProperty --|> Geometry  #00008B 
Card SpatialLocation #F0F8FF [
SpatialLocation
]
Geometry --|> SpatialLocation  #00008B 
Card Trajectory #F0F8FF [
Trajectory
----
- obstructedBy : PhysicalObjectState 
]
Geometry --|> Trajectory  #00008B 
@enduml