@startuml
Title InstalledFunctionalSystemComponent 

Card InstalledFunctionalSystemComponent #F0F8FF [
InstalledFunctionalSystemComponent
]
Card FunctionalSystemComponentState #F0F8FF [
FunctionalSystemComponentState
]
FunctionalSystemComponentState --|> InstalledFunctionalSystemComponent  #00008B 
Card InstalledObject #F0F8FF [
InstalledObject
]
InstalledObject --|> InstalledFunctionalSystemComponent  #00008B 
@enduml