@startuml
Title InstalledObject 

Card InstalledObject #F0F8FF [
InstalledObject
]
Card OrdinaryPhysicalObjectState #F0F8FF [
OrdinaryPhysicalObjectState
]
OrdinaryPhysicalObjectState --|> InstalledObject  #00008B 
Card InstalledFunctionalSystemComponent #F0F8FF [
InstalledFunctionalSystemComponent
]
InstalledFunctionalSystemComponent <|-- InstalledObject  #00008B 
@enduml