@startuml
Title IntentionallyConstructedObjectState 

Card IntentionallyConstructedObjectState #F0F8FF [
IntentionallyConstructedObjectState
]
Card State #F0F8FF [
State
]
State --|> IntentionallyConstructedObjectState  #00008B 
Card FunctionalObjectState #F0F8FF [
FunctionalObjectState
----
- intendedRole : Role 
]
IntentionallyConstructedObjectState --|> FunctionalObjectState  #00008B 
Card WholeLifeIntentionallyConstructedObject #F0F8FF [
WholeLifeIntentionallyConstructedObject
]
IntentionallyConstructedObjectState --|> WholeLifeIntentionallyConstructedObject  #00008B 
@enduml