@startuml
Title Kind 

Card Kind #F0F8FF [
Kind
]
Card Set #F0F8FF [
Set
]
Set --|> Kind  #00008B 
Card KindOfActivityStates #F0F8FF [
KindOfActivityStates
]
KindOfActivityStates <|-- Kind  #00008B 
Card KindOfPhysicalObjectStates #F0F8FF [
KindOfPhysicalObjectStates
]
KindOfPhysicalObjectStates <|-- Kind  #00008B 
Card Role #F0F8FF [
Role
]
Role <|-- Kind  #00008B 
@enduml