@startuml
Title KindOfPhysicalObjectStates 

Card KindOfPhysicalObjectStates #F0F8FF [
KindOfPhysicalObjectStates
]
Card Kind #F0F8FF [
Kind
]
Kind --|> KindOfPhysicalObjectStates  #00008B 
Card SetOfPhysicalObjectStates #F0F8FF [
SetOfPhysicalObjectStates
]
SetOfPhysicalObjectStates --|> KindOfPhysicalObjectStates  #00008B 
@enduml