@startuml
Title KindOfActivityStates 

Card KindOfActivityStates #F0F8FF [
KindOfActivityStates
]
Card Kind #F0F8FF [
Kind
]
Kind --|> KindOfActivityStates  #00008B 
Card SetOfActivityStates #F0F8FF [
SetOfActivityStates
]
SetOfActivityStates --|> KindOfActivityStates  #00008B 
@enduml