@startuml
Title Kind 

Card Kind #F0F8FF [
Kind
]
Card Set #F0F8FF [
Set
]
Set --|> Kind  #00008B 
Card KindOfActivityStates #F0F8FF [
KindOfActivityStates
]
Kind --|> KindOfActivityStates  #00008B 
Card KindOfPhysicalObjectStates #F0F8FF [
KindOfPhysicalObjectStates
]
Kind --|> KindOfPhysicalObjectStates  #00008B 
Card Role #F0F8FF [
Role
]
Kind --|> Role  #00008B 
@enduml