@startuml
Title Participant 

Card Participant #F0F8FF [
Participant
----
- participantOf : ActivityState 
]
Card PhysicalObjectState #F0F8FF [
PhysicalObjectState
----
- connectedTo : PhysicalObjectState 
- hasRelativePosition : PhysicalObjectState 
]
PhysicalObjectState --|> Participant  #00008B 
Card TrafficParticipant #F0F8FF [
TrafficParticipant
]
Participant --|> TrafficParticipant  #00008B 
@enduml