@startuml
Title PeriodOfTime 

Card PeriodOfTime #F0F8FF [
PeriodOfTime
]
Card State #F0F8FF [
State
]
State --|> PeriodOfTime  #00008B 
Card PossibleWorld #F0F8FF [
PossibleWorld
]
PeriodOfTime --|> PossibleWorld  #00008B 
@enduml