@startuml
Title PhysicalObjectState 

Card PhysicalObjectState #F0F8FF [
PhysicalObjectState
----
- connectedTo : PhysicalObjectState 
- hasRelativePosition : PhysicalObjectState 
]
Card State #F0F8FF [
State
]
State --|> PhysicalObjectState  #00008B 
Card BiologicalObjectState #F0F8FF [
BiologicalObjectState
]
PhysicalObjectState --|> BiologicalObjectState  #00008B 
Card FunctionalObjectState #F0F8FF [
FunctionalObjectState
----
- intendedRole : Role 
]
PhysicalObjectState --|> FunctionalObjectState  #00008B 
Card OrdinaryPhysicalObjectState #F0F8FF [
OrdinaryPhysicalObjectState
]
PhysicalObjectState --|> OrdinaryPhysicalObjectState  #00008B 
Card Participant #F0F8FF [
Participant
----
- participantOf : ActivityState 
]
PhysicalObjectState --|> Participant  #00008B 
Card SystemComponentState #F0F8FF [
SystemComponentState
----
- componentOf : SystemState 
]
PhysicalObjectState --|> SystemComponentState  #00008B 
Card WholeLifePhysicalObject #F0F8FF [
WholeLifePhysicalObject
]
PhysicalObjectState --|> WholeLifePhysicalObject  #00008B 
@enduml