@startuml
Title PhysicalQuantity 

Card PhysicalQuantity #F0F8FF [
PhysicalQuantity
----
- approximatelyEqualTo : PhysicalQuantity 
- defines : PhysicalQuantity 
- hasQuantityRelation : PhysicalQuantity 
- quantityEqualTo : PhysicalQuantity 
- quantityGreaterThan : PhysicalQuantity 
- quantityGreaterThanOrEqualTo : PhysicalQuantity 
- quantityLessThan : PhysicalQuantity 
- quantityLessThanOrEqualTo : PhysicalQuantity 
- quantityNotEqualTo : PhysicalQuantity 
]
Card PhysicalProperty #F0F8FF [
PhysicalProperty
]
PhysicalProperty --|> PhysicalQuantity  #00008B 
Card AngleQuantity #F0F8FF [
AngleQuantity
]
PhysicalQuantity --|> AngleQuantity  #00008B 
Card DirectionQuantity #F0F8FF [
DirectionQuantity
----
- oppositeOf : DirectionQuantity 
- parallelTo : DirectionQuantity 
]
PhysicalQuantity --|> DirectionQuantity  #00008B 
Card LengthQuantity #F0F8FF [
LengthQuantity
]
PhysicalQuantity --|> LengthQuantity  #00008B 
Card SpeedQuantity #F0F8FF [
SpeedQuantity
]
PhysicalQuantity --|> SpeedQuantity  #00008B 
@enduml