@startuml
Title PossibleWorld 

Card PossibleWorld #F0F8FF [
PossibleWorld
]
Card PeriodOfTime #F0F8FF [
PeriodOfTime
]
PeriodOfTime --|> PossibleWorld  #00008B 
Card WholeLifeIndividual #F0F8FF [
WholeLifeIndividual
]
WholeLifeIndividual --|> PossibleWorld  #00008B 
@enduml