@startuml
Title RelativeLocation 

Card RelativeLocation #F0F8FF [
RelativeLocation
----
- hasEdgeAlignment : EdgeAlignmentType 
- hasXoffset : LengthQuantity 
- hasYoffset : LengthQuantity 
]
Card SpatialLocation #F0F8FF [
SpatialLocation
]
SpatialLocation --|> RelativeLocation  #00008B 
Card SpatialRelation #F0F8FF [
SpatialRelation
----
- hasRelationDirection : DirectionQuantity 
- hasSpatialObject : PhysicalObjectState 
- hasSpatialSubject : PhysicalObjectState 
]
SpatialRelation --|> RelativeLocation  #00008B 
@enduml