@startuml
Title Relationship 

Card Relationship #F0F8FF [
Relationship
]
Card AbstractObject #F0F8FF [
AbstractObject
]
AbstractObject --|> Relationship  #00008B 
Card Aggregation #F0F8FF [
Aggregation
----
- part : SpatioTemporalExtent 
- whole : SpatioTemporalExtent 
]
Relationship --|> Aggregation  #00008B 
Card Classification #F0F8FF [
Classification
----
- classifier : Set 
]
Relationship --|> Classification  #00008B 
Card DefinedRelationship #F0F8FF [
DefinedRelationship
----
- involves : Classification 
]
Relationship --|> DefinedRelationship  #00008B 
@enduml