@startuml
Title RoadObject 

Card RoadObject #F0F8FF [
RoadObject
----
- driveableTo : RoadObject 
- hasPredecessor : RoadObject 
- hasSuccessor : RoadObject 
]
Card FunctionalSystemComponentState #F0F8FF [
FunctionalSystemComponentState
]
FunctionalSystemComponentState --|> RoadObject  #00008B 
@enduml