@startuml
Title Role 

Card Role #F0F8FF [
Role
]
Card Kind #F0F8FF [
Kind
]
Kind --|> Role  #00008B 
Card SetOfParticipants #F0F8FF [
SetOfParticipants
]
SetOfParticipants --|> Role  #00008B 
@enduml