@startuml
Title RuleViolatingEntity 

Card RuleViolatingEntity #F0F8FF [
RuleViolatingEntity
----
- violatesTrafficRule : TrafficRule 
]
Card State #F0F8FF [
State
]
State --|> RuleViolatingEntity  #00008B 
@enduml