@startuml
Title SeparationDistance 

Card SeparationDistance #fff [
SeparationDistance
----
- occludedBy : PhysicalObjectState 

]
Card SpatialRelation #fff [
SpatialRelation
----
- hasRelationDirection : DirectionQuantity 
- hasSpatialObject : PhysicalObjectState 
- hasSpatialSubject : PhysicalObjectState 

]
SpatialRelation --|> SeparationDistance  #000 
@enduml