@startuml
Title SeparationDistance 

Card SeparationDistance #F0F8FF [
SeparationDistance
----
- occludedBy : PhysicalObjectState 
]
Card SpatialRelation #F0F8FF [
SpatialRelation
----
- hasRelationDirection : DirectionQuantity 
- hasSpatialObject : PhysicalObjectState 
- hasSpatialSubject : PhysicalObjectState 
]
SpatialRelation --|> SeparationDistance  #00008B 
@enduml