@startuml
Title Set 

Card Set #F0F8FF [
Set
]
Card AbstractObject #F0F8FF [
AbstractObject
]
AbstractObject --|> Set  #00008B 
Card Kind #F0F8FF [
Kind
]
Kind <|-- Set  #00008B 
Card SetOfSpatioTemporalExtents #F0F8FF [
SetOfSpatioTemporalExtents
]
SetOfSpatioTemporalExtents <|-- Set  #00008B 
@enduml