@startuml
Title SetOfParticipants 

Card SetOfParticipants #F0F8FF [
SetOfParticipants
]
Card SetOfPhysicalObjectStates #F0F8FF [
SetOfPhysicalObjectStates
]
SetOfPhysicalObjectStates --|> SetOfParticipants  #00008B 
Card Role #F0F8FF [
Role
]
Role <|-- SetOfParticipants  #00008B 
@enduml