@startuml
Title SetOfEvents 

Card SetOfEvents #F0F8FF [
SetOfEvents
]
Card SetOfSpatioTemporalExtents #F0F8FF [
SetOfSpatioTemporalExtents
]
SetOfSpatioTemporalExtents --|> SetOfEvents  #00008B 
@enduml