@startuml
Title SetOfWholeLifeIndividuals 

Card SetOfWholeLifeIndividuals #F0F8FF [
SetOfWholeLifeIndividuals
]
Card SetOfStates #F0F8FF [
SetOfStates
]
SetOfStates --|> SetOfWholeLifeIndividuals  #00008B 
@enduml