@startuml
Title SetOfSpatioTemporalExtents 

Card SetOfSpatioTemporalExtents #F0F8FF [
SetOfSpatioTemporalExtents
]
Card Set #F0F8FF [
Set
]
Set --|> SetOfSpatioTemporalExtents  #00008B 
Card SetOfEvents #F0F8FF [
SetOfEvents
]
SetOfEvents <|-- SetOfSpatioTemporalExtents  #00008B 
Card SetOfStates #F0F8FF [
SetOfStates
]
SetOfStates <|-- SetOfSpatioTemporalExtents  #00008B 
@enduml