@startuml
Title SetOfStates 

Card SetOfStates #F0F8FF [
SetOfStates
]
Card SetOfSpatioTemporalExtents #F0F8FF [
SetOfSpatioTemporalExtents
]
SetOfSpatioTemporalExtents --|> SetOfStates  #00008B 
Card PhysicalProperty #F0F8FF [
PhysicalProperty
]
SetOfStates --|> PhysicalProperty  #00008B 
Card SetOfActivityStates #F0F8FF [
SetOfActivityStates
]
SetOfStates --|> SetOfActivityStates  #00008B 
Card SetOfPhysicalObjectStates #F0F8FF [
SetOfPhysicalObjectStates
]
SetOfStates --|> SetOfPhysicalObjectStates  #00008B 
Card SetOfWholeLifeIndividuals #F0F8FF [
SetOfWholeLifeIndividuals
]
SetOfStates --|> SetOfWholeLifeIndividuals  #00008B 
@enduml