@startuml
Title SetOfActivityStates 

Card SetOfActivityStates #F0F8FF [
SetOfActivityStates
]
Card SetOfStates #F0F8FF [
SetOfStates
]
SetOfStates --|> SetOfActivityStates  #00008B 
Card KindOfActivityStates #F0F8FF [
KindOfActivityStates
]
KindOfActivityStates <|-- SetOfActivityStates  #00008B 
@enduml