@startuml
Title SetOfPhysicalObjectStates 

Card SetOfPhysicalObjectStates #F0F8FF [
SetOfPhysicalObjectStates
]
Card SetOfStates #F0F8FF [
SetOfStates
]
SetOfStates --|> SetOfPhysicalObjectStates  #00008B 
Card KindOfPhysicalObjectStates #F0F8FF [
KindOfPhysicalObjectStates
]
KindOfPhysicalObjectStates <|-- SetOfPhysicalObjectStates  #00008B 
Card SetOfParticipants #F0F8FF [
SetOfParticipants
]
SetOfParticipants <|-- SetOfPhysicalObjectStates  #00008B 
@enduml