@startuml
Title SpatialRelation 

Card SpatialRelation #F0F8FF [
SpatialRelation
----
- hasRelationDirection : DirectionQuantity 
- hasSpatialObject : PhysicalObjectState 
- hasSpatialSubject : PhysicalObjectState 
]
Card DefinedRelationship #F0F8FF [
DefinedRelationship
----
- involves : Classification 
]
DefinedRelationship --|> SpatialRelation  #00008B 
Card RelativeLocation #F0F8FF [
RelativeLocation
----
- hasEdgeAlignment : EdgeAlignmentType 
- hasXoffset : LengthQuantity 
- hasYoffset : LengthQuantity 
]
SpatialRelation --|> RelativeLocation  #00008B 
Card SeparationDistance #F0F8FF [
SeparationDistance
----
- occludedBy : PhysicalObjectState 
]
SpatialRelation --|> SeparationDistance  #00008B 
Card SpatialConnection #F0F8FF [
SpatialConnection
]
SpatialRelation --|> SpatialConnection  #00008B 
@enduml