@startuml
Title SpatioTemporalExtent 

Card SpatioTemporalExtent #F0F8FF [
SpatioTemporalExtent
----
- aggregatedInto : SpatioTemporalExtent 
- hasPart : SpatioTemporalExtent 
]
Card Thing #F0F8FF [
Thing
]
Thing --|> SpatioTemporalExtent  #00008B 
Card Event #F0F8FF [
Event
----
- hasRelativeTime : Event 
]
SpatioTemporalExtent --|> Event  #00008B 
Card State #F0F8FF [
State
]
SpatioTemporalExtent --|> State  #00008B 
@enduml