@startuml
Title SpatialLocation 

Card SpatialLocation #F0F8FF [
SpatialLocation
]
Card Geometry #F0F8FF [
Geometry
]
Geometry --|> SpatialLocation  #00008B 
Card RelativeLocation #F0F8FF [
RelativeLocation
----
- hasEdgeAlignment : EdgeAlignmentType 
- hasXoffset : LengthQuantity 
- hasYoffset : LengthQuantity 
]
SpatialLocation --|> RelativeLocation  #00008B 
@enduml