@startuml
Title SpeedQuantity 

Card SpeedQuantity #F0F8FF [
SpeedQuantity
]
Card PhysicalQuantity #F0F8FF [
PhysicalQuantity
----
- approximatelyEqualTo : PhysicalQuantity 
- defines : PhysicalQuantity 
- hasQuantityRelation : PhysicalQuantity 
- quantityEqualTo : PhysicalQuantity 
- quantityGreaterThan : PhysicalQuantity 
- quantityGreaterThanOrEqualTo : PhysicalQuantity 
- quantityLessThan : PhysicalQuantity 
- quantityLessThanOrEqualTo : PhysicalQuantity 
- quantityNotEqualTo : PhysicalQuantity 
]
PhysicalQuantity --|> SpeedQuantity  #00008B 
@enduml