@startuml
Title State 

Card State #F0F8FF [
State
]
Card SpatioTemporalExtent #F0F8FF [
SpatioTemporalExtent
----
- aggregatedInto : SpatioTemporalExtent 
- hasPart : SpatioTemporalExtent 
]
SpatioTemporalExtent --|> State  #00008B 
Card ActivityState #F0F8FF [
ActivityState
----
- causes : Event 
- hasParticipant : Participant 
]
State --|> ActivityState  #00008B 
Card ControllerObject #F0F8FF [
ControllerObject
----
- controls : SpatioTemporalExtent 
]
State --|> ControllerObject  #00008B 
Card IntentionallyConstructedObjectState #F0F8FF [
IntentionallyConstructedObjectState
]
State --|> IntentionallyConstructedObjectState  #00008B 
Card PeriodOfTime #F0F8FF [
PeriodOfTime
]
State --|> PeriodOfTime  #00008B 
Card PhysicalObjectState #F0F8FF [
PhysicalObjectState
----
- connectedTo : PhysicalObjectState 
- hasRelativePosition : PhysicalObjectState 
]
State --|> PhysicalObjectState  #00008B 
Card RuleViolatingEntity #F0F8FF [
RuleViolatingEntity
----
- violatesTrafficRule : TrafficRule 
]
State --|> RuleViolatingEntity  #00008B 
Card WholeLifeIndividual #F0F8FF [
WholeLifeIndividual
]
State --|> WholeLifeIndividual  #00008B 
@enduml