@startuml
Title SystemComponentState 

Card SystemComponentState #F0F8FF [
SystemComponentState
----
- componentOf : SystemState 
]
Card PhysicalObjectState #F0F8FF [
PhysicalObjectState
----
- connectedTo : PhysicalObjectState 
- hasRelativePosition : PhysicalObjectState 
]
PhysicalObjectState --|> SystemComponentState  #00008B 
Card FunctionalSystemComponentState #F0F8FF [
FunctionalSystemComponentState
]
SystemComponentState --|> FunctionalSystemComponentState  #00008B 
Card WholeLifeSystemComponent #F0F8FF [
WholeLifeSystemComponent
]
SystemComponentState --|> WholeLifeSystemComponent  #00008B 
@enduml