@startuml
Title SystemState 

Card SystemState #F0F8FF [
SystemState
]
Card OrdinaryPhysicalObjectState #F0F8FF [
OrdinaryPhysicalObjectState
]
OrdinaryPhysicalObjectState --|> SystemState  #00008B 
Card FunctionalSystemState #F0F8FF [
FunctionalSystemState
]
SystemState --|> FunctionalSystemState  #00008B 
Card WholeLifeSystem #F0F8FF [
WholeLifeSystem
]
SystemState --|> WholeLifeSystem  #00008B 
@enduml