@startuml
Title TemporalRelation 

Card TemporalRelation #F0F8FF [
TemporalRelation
]
Card DefinedRelationship #F0F8FF [
DefinedRelationship
----
- involves : Classification 
]
DefinedRelationship --|> TemporalRelation  #00008B 
@enduml