@startuml
Title WholeLifeBiologicalObject 

Card WholeLifeBiologicalObject #F0F8FF [
WholeLifeBiologicalObject
]
Card BiologicalObjectState #F0F8FF [
BiologicalObjectState
]
BiologicalObjectState --|> WholeLifeBiologicalObject  #00008B 
Card WholeLifePhysicalObject #F0F8FF [
WholeLifePhysicalObject
]
WholeLifePhysicalObject --|> WholeLifeBiologicalObject  #00008B 
@enduml