@startuml
Title WholeLifeOrdinaryPhysicalObject 

Card WholeLifeOrdinaryPhysicalObject #F0F8FF [
WholeLifeOrdinaryPhysicalObject
]
Card OrdinaryPhysicalObjectState #F0F8FF [
OrdinaryPhysicalObjectState
]
OrdinaryPhysicalObjectState --|> WholeLifeOrdinaryPhysicalObject  #00008B 
Card WholeLifePhysicalObject #F0F8FF [
WholeLifePhysicalObject
]
WholeLifePhysicalObject --|> WholeLifeOrdinaryPhysicalObject  #00008B 
@enduml