@startuml
Title WholeLifeFunctionalObject 

Card WholeLifeFunctionalObject #F0F8FF [
WholeLifeFunctionalObject
]
Card FunctionalObjectState #F0F8FF [
FunctionalObjectState
----
- intendedRole : Role 
]
FunctionalObjectState --|> WholeLifeFunctionalObject  #00008B 
Card WholeLifeIntentionallyConstructedObject #F0F8FF [
WholeLifeIntentionallyConstructedObject
]
WholeLifeIntentionallyConstructedObject --|> WholeLifeFunctionalObject  #00008B 
Card WholeLifePhysicalObject #F0F8FF [
WholeLifePhysicalObject
]
WholeLifePhysicalObject --|> WholeLifeFunctionalObject  #00008B 
@enduml