@startuml
Title WholeLifeSystemComponent 

Card WholeLifeSystemComponent #F0F8FF [
WholeLifeSystemComponent
]
Card SystemComponentState #F0F8FF [
SystemComponentState
----
- componentOf : SystemState 
]
SystemComponentState --|> WholeLifeSystemComponent  #00008B 
Card WholeLifePhysicalObject #F0F8FF [
WholeLifePhysicalObject
]
WholeLifePhysicalObject --|> WholeLifeSystemComponent  #00008B 
@enduml