@startuml
Title WholeLifeActivity 

Card WholeLifeActivity #F0F8FF [
WholeLifeActivity
]
Card ActivityState #F0F8FF [
ActivityState
----
- causes : Event 
- hasParticipant : Participant 
]
ActivityState --|> WholeLifeActivity  #00008B 
Card WholeLifeIndividual #F0F8FF [
WholeLifeIndividual
]
WholeLifeIndividual --|> WholeLifeActivity  #00008B 
@enduml