@startuml
Title WholeLifeIntentionallyConstructedObject 

Card WholeLifeIntentionallyConstructedObject #F0F8FF [
WholeLifeIntentionallyConstructedObject
]
Card IntentionallyConstructedObjectState #F0F8FF [
IntentionallyConstructedObjectState
]
IntentionallyConstructedObjectState --|> WholeLifeIntentionallyConstructedObject  #00008B 
Card WholeLifeIndividual #F0F8FF [
WholeLifeIndividual
]
WholeLifeIndividual --|> WholeLifeIntentionallyConstructedObject  #00008B 
Card WholeLifeFunctionalObject #F0F8FF [
WholeLifeFunctionalObject
]
WholeLifeFunctionalObject <|-- WholeLifeIntentionallyConstructedObject  #00008B 
@enduml