@startuml
Title WholeLifeIntentionallyConstructedObject 

Card WholeLifeIntentionallyConstructedObject #fff [
WholeLifeIntentionallyConstructedObject
]
Card IntentionallyConstructedObjectState #fff [
IntentionallyConstructedObjectState
]
IntentionallyConstructedObjectState --|> WholeLifeIntentionallyConstructedObject  #000 
Card WholeLifeIndividual #fff [
WholeLifeIndividual
]
WholeLifeIndividual --|> WholeLifeIntentionallyConstructedObject  #000 
@enduml