@startuml
Title WholeLifeIndividual 

Card WholeLifeIndividual #F0F8FF [
WholeLifeIndividual
]
Card State #F0F8FF [
State
]
State --|> WholeLifeIndividual  #00008B 
Card PossibleWorld #F0F8FF [
PossibleWorld
]
WholeLifeIndividual --|> PossibleWorld  #00008B 
Card WholeLifeActivity #F0F8FF [
WholeLifeActivity
]
WholeLifeIndividual --|> WholeLifeActivity  #00008B 
Card WholeLifeIntentionallyConstructedObject #F0F8FF [
WholeLifeIntentionallyConstructedObject
]
WholeLifeIndividual --|> WholeLifeIntentionallyConstructedObject  #00008B 
Card WholeLifePhysicalObject #F0F8FF [
WholeLifePhysicalObject
]
WholeLifeIndividual --|> WholeLifePhysicalObject  #00008B 
@enduml